FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive \
    TZ=UTC \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

RUN apt-get update && apt-get install -y \
    curl ca-certificates gnupg lsb-release \
    git bash zsh neovim tmux jq \
    python3 python3-pip python3-venv \
    nodejs npm \
    golang-go \
    wget \
    && rm -rf /var/lib/apt/lists/*

# --- kubectl ---
RUN curl -fsSLo /usr/local/bin/kubectl \
      "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
    && chmod +x /usr/local/bin/kubectl

# --- Helm ---
RUN curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

# --- k9s (nice to have) ---
RUN K9S_VERSION="v0.32.5" && \
    curl -L "https://github.com/derailed/k9s/releases/download/${K9S_VERSION}/k9s_Linux_amd64.tar.gz" \
    | tar xz -C /usr/local/bin k9s

# Create workspace folder
RUN mkdir -p /workspace
WORKDIR /workspace
